### ISSUE TITLE
Implement tbDEX Resource parsing

### ISSUE THREAD

**Issue by amika-sq** [TBD54566975/tbdex-rs#18]
Given a JSON payload, parse into a tbDEX Resource object

**Comment by KendallWeihe** [comment]
we'll only currently offer parsing at the resource-kind level (offering or balance) and not at the resource level (although we could make it work, it's not what we expose in other SDKs and it's unclear if it would be valuable. closing this ticket, will open distinct tickets for the given parsers needed.
