### ISSUE TITLE
Refactor CI

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/tbdex-rs#94]
This task encompasses a refactoring of the GitHub Actions CI as well as the Kotlin `pom.xml`.

Maintain all build features of `tbdex-kt`:

* Docs
* Code Coverage
* Signing (GPG)
* Publishing (`SNAPSHOT`s to TBD Artifactory; Releases may be handled in a new issue)

For the Rust Core:
* Build all native binaries in their appropriate environments
* Place the native binaries into the Kotlin distribution
* Build and test the Kotlin distribution

**Comment by ALRubinger** [comment]
Q for @KendallWeihe @nitro-neal: Can we fix Java version from `11`, which is EOL, to at least `17`?

**Comment by ALRubinger** [comment]
Q to review with @KendallWeihe and @nitro-neal on Monday, from comments I'm dropping into the `pom.xml`:

```
ALR NOTE for Issue #94: This description is currently out of date
        as of right now we are making this a single module build, not a multi-module
        with a BOM POM. Reviewing later with NealR and Kendall whether we should at least
        make this a multimodule with one module so we can get better transitive dependency
        management via a BOM POM.
```

**Comment by KendallWeihe** [comment]
> Reviewing later with NealR and Kendall whether we should at least
        make this a multimodule with one module so we can get better transitive dependency
        management via a BOM POM.

Not opposed! If you can fit it into the workload then I'm open to it 👍 

The general strategy here is to start as a bundle and move to atomized packages, and that I think should remain the case for the time being.

**Comment by ALRubinger** [comment]
> > Reviewing later with NealR and Kendall whether we should at least
> > make this a multimodule with one module so we can get better transitive dependency
> > management via a BOM POM.
> 
> Not opposed! If you can fit it into the workload then I'm open to it 👍
> 
> The general strategy here is to start as a bundle and move to atomized packages, and that I think should remain the case for the time being.

Let's do this in some future task. Not necessary to cross the upcoming deliverables.

**Comment by ALRubinger** [comment]
Done in aa3e465
